// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Useful to verify connectivity to BRUChat MCP.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool2({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in BRUChat user's profile (id, username, display name).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("profiles").select("id, username, display_name, bio").eq("id", ctx.getUserId()).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-conversations.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_conversations_default = defineTool3({
  name: "list_conversations",
  title: "List conversations",
  description: "List the signed-in user's most recent direct-message conversations with the other participant's profile.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max conversations to return (default 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb2(ctx);
    const uid = ctx.getUserId();
    const { data: convos, error } = await client.from("conversations").select("id, participant_a, participant_b, last_message_at").or(`participant_a.eq.${uid},participant_b.eq.${uid}`).order("last_message_at", { ascending: false }).limit(limit ?? 20);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    const otherIds = (convos ?? []).map((c) => c.participant_a === uid ? c.participant_b : c.participant_a);
    const { data: profiles } = otherIds.length ? await client.from("profiles").select("id, username, display_name").in("id", otherIds) : { data: [] };
    const map = {};
    (profiles ?? []).forEach((p) => {
      map[p.id] = p;
    });
    const items = (convos ?? []).map((c) => {
      const otherId = c.participant_a === uid ? c.participant_b : c.participant_a;
      return {
        conversation_id: c.id,
        last_message_at: c.last_message_at,
        other_user: map[otherId] ?? { id: otherId }
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { conversations: items }
    };
  }
});

// src/lib/mcp/tools/read-messages.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var read_messages_default = defineTool4({
  name: "read_messages",
  title: "Read messages",
  description: "Fetch the most recent messages from a direct-message conversation the user participates in.",
  inputSchema: {
    conversation_id: z3.string().uuid().describe("Conversation ID (from list_conversations)."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max messages (default 30).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ conversation_id, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb3(ctx).from("messages").select("id, sender_id, content, created_at, message_type, image_url, video_url, audio_url").eq("conversation_id", conversation_id).eq("is_deleted", false).order("created_at", { ascending: false }).limit(limit ?? 30);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    const ordered = (data ?? []).slice().reverse();
    return {
      content: [{ type: "text", text: JSON.stringify(ordered, null, 2) }],
      structuredContent: { messages: ordered }
    };
  }
});

// src/lib/mcp/tools/send-message.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var send_message_default = defineTool5({
  name: "send_message",
  title: "Send message",
  description: "Send a plain-text message from the signed-in user into an existing direct-message conversation.",
  inputSchema: {
    conversation_id: z4.string().uuid().describe("Target conversation ID."),
    text: z4.string().trim().min(1).describe("Message body to send.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ conversation_id, text }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb4(ctx);
    const { data, error } = await client.from("messages").insert({
      conversation_id,
      sender_id: ctx.getUserId(),
      content: text,
      message_type: "text"
    }).select("id, created_at").single();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    await client.from("conversations").update({ last_message_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", conversation_id);
    return {
      content: [{ type: "text", text: `Sent message ${data.id}` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/tools/list-notifications.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_notifications_default = defineTool6({
  name: "list_notifications",
  title: "List notifications",
  description: "List the signed-in user's recent notifications.",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).optional().describe("Max notifications (default 20)."),
    unread_only: z5.boolean().optional().describe("Return only unread notifications.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit, unread_only }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb5(ctx).from("notifications").select("id, type, from_user_id, conversation_id, group_id, is_read, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (unread_only) q = q.eq("is_read", false);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { notifications: data }
    };
  }
});

// src/lib/mcp/tools/create-post.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^4.4.3";
function sb6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_post_default = defineTool7({
  name: "create_post",
  title: "Create post",
  description: "Publish a new text post on the BRUChat social feed as the signed-in user.",
  inputSchema: {
    content: z6.string().trim().min(1).describe("Post body text."),
    is_public: z6.boolean().optional().describe("Public visibility (default true).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ content, is_public }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb6(ctx).from("posts").insert({
      user_id: ctx.getUserId(),
      content,
      is_public: is_public ?? true,
      post_type: "text"
    }).select("id, created_at").single();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Post created: ${data.id}` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-recent-posts.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z7 } from "npm:zod@^4.4.3";
function sb7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_posts_default = defineTool8({
  name: "list_recent_posts",
  title: "List recent posts",
  description: "List recent public posts on the BRUChat feed.",
  inputSchema: {
    limit: z7.number().int().min(1).max(50).optional().describe("Max posts (default 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb7(ctx).from("posts").select("id, user_id, content, likes_count, comments_count, created_at").eq("is_public", true).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "evqstxlozkqzlckykkil";
var mcp_default = defineMcp({
  name: "bruchat-mcp",
  title: "BRUChat MCP",
  version: "0.1.0",
  instructions: "Tools for BRUChat, a messenger and social app. Use `whoami` to identify the user, `list_conversations` and `read_messages` to browse DMs, `send_message` to reply, `list_notifications` for activity, and `list_recent_posts`/`create_post` for the social feed. Use `echo` to verify connectivity.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    echo_default,
    whoami_default,
    list_conversations_default,
    read_messages_default,
    send_message_default,
    list_notifications_default,
    create_post_default,
    list_recent_posts_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
